name: Rainfall
version: 1.0.0
main: com.blockymmc.rainfall.RainfallPlugin
api-version: '1.21'
authors: [BlockyMC]
depend: [AdvancedEnchantments, Nexo]

commands:
  rainfall:
    description: Give a seasonal crate item to a player
    usage: /rainfall <player> <itemId>
    permission: rainfall.give
